BOT_TOKEN: 8164463105:AAEoCDa1uRiOg0M6sQs-mWVeBsa-0xp5U3U
OWNER_ID: 949657126
DATABASE_URL: mongodb+srv://avatarr112200:6pnK1K3d1Gg9CaIW@cluster0.nmglsmd.mongodb.net/?appName=Cluster0
TELEGRAM_API: 29961422
TELEGRAM_HASH: cba915c79809dc0806676db7052b2a83
HEROKU_APP_NAME: mll-bot
HEROKU_EMAIL: Hawkeye11220@gmail.com 
HEROKU_API_KEY: HRKU-AAfL-f_SKI50fEjBR-pet-uo0omYrFQTmmg5A6_wWOLw_____waxDDVSmIbY
